name: thesis-code
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - networkx
  - pytorch::pytorch
  - pytorch-cuda=12.4
  - tqdm
  - pip
  - pip:
      - r2pipe
      - bert-pytorch
